api/src/utils/agents/generate_sql_agent.rs, api/src/utils/prompts/generate_sql_prompts/sql_gen_prompt.rs, api/src/utils/prompts/generate_sql_prompts/sql_gen_thought_prompt.rs
- Added support for retrieving and passing data source type during SQL agent generation
- Updated SQL generation prompts to include data source type in system messages
- Modified `generate_sql_agent` function to fetch and utilize data source type information
- Improved SQL generation context by dynamically incorporating data source type details
=> chore: Enhance SQL agent generation with data source type context

api/src/utils/agents/modify_visualization_agent.rs, api/src/utils/prompts/modify_visualization_prompts/build_charts_prompts/bar_line_chart_prompt.rs, api/src/utils/prompts/modify_visualization_prompts/build_charts_prompts/combo_chart_prompt.rs, api/src/utils/prompts/modify_visualization_prompts/format_label_prompt.rs, web/src/api/buster_rest/threads/defaults.ts, web/src/app/app/_controllers/ThreadController/ThreadControllerEditContent/SidebarStylingApp/StylingAppVisualize/SelectAxis/SelectAxis.tsx, web/src/app/app/_controllers/ThreadController/ThreadControllerEditContent/SidebarStylingApp/StylingAppVisualize/SelectAxis/useSelectAxisContext.tsx, web/src/app/app/_controllers/ThreadController/ThreadControllerEditContent/SidebarStylingApp/StylingAppVisualize/StylingAppVisualize.tsx, web/src/app/test/chartjs/chartjsfixedline/page.tsx, web/src/components/charts/BusterChartJS/BusterChartJSComponent.tsx, web/src/components/charts/BusterChartJS/hooks/useOptions/useOptions.tsx, web/src/components/charts/BusterChartJS/hooks/useOptions/useXAxis.ts, web/src/components/charts/interfaces/tickInterfaces.ts
* xAxisTickinerval
* fix(visualization): Add x-axis time unit configuration for bar and combo charts
- Extend chart configuration to support optional x-axis time unit
- Update modify visualization agent to dynamically set x-axis time interval
- Modify bar line and combo chart prompts to include x_axis_time_unit parameter
* only use valid time units
* refactor(visualization): Simplify x-axis time unit configuration
- Modify modify_visualization_agent to extract and remove x-axis time unit more efficiently
- Update global styling result structure for x-axis time interval
- Adjust format_label_prompt comment to clarify date format default behavior
---------
=> fix(visualization): add x axis time unit.

api/src/utils/query_engine/data_source_query_routes/snowflake_query.rs
- Add support for parsing Snowflake timestamp structs with epoch and fraction fields
- Implement handling of Snowflake timestamp logical types (with and without timezone)
- Enhance JSON value processing to detect and convert Snowflake timestamp objects
- Add error handling and logging for timestamp parsing
=> fix(snowflake): Improve timestamp handling and JSON processing

cli/Cargo.toml, cli/src/commands/deploy.rs, cli/src/commands/generate.rs, cli/src/commands/init.rs, cli/src/utils/exclusion.rs, cli/src/utils/file_finder.rs, cli/src/utils/mod.rs
model path bug
init overwrite bug
=> Cli Improvements

packages/ai/src/tools/visualization-tools/create-metrics-file-tool.ts
Fixed combo charts so they actually add the y2
=> combo chart fixes

packages/ai/src/agents/analyst-agent/analyst-agent-instructions.ts, packages/ai/src/tools/visualization-tools/modify-metrics-file-tool.ts
fixes for horizontal bar charts so that the axis don't get flipped and added the combo chart logic to update metric
=> Horizontal bar fixes

apps/server/src/api/v2/chats/handler.test.ts, apps/server/src/api/v2/chats/services/chat-helpers.test.ts, apps/server/src/api/v2/chats/services/chat-helpers.ts, apps/server/src/api/v2/chats/services/chat-service.test.ts, packages/database/src/helpers/chats.ts, packages/database/src/helpers/index.ts
Integrate `canUserAccessChatCached` for chat follow-up permissions to properly include organization admin access.
=> Update chat follow-up permissions for admins

packages/ai/package.json, packages/ai/src/agents/analyst-agent/analyst-agent-instructions.ts, packages/ai/src/agents/think-and-prep-agent/think-and-prep-instructions.ts
Changes to the logic for when to pick horizontal vs vertical bar charts as well as logic that tries to push it to use precomputed metrics when possible.
=> Jacob prompt changes v2

packages/ai/src/agents/think-and-prep-agent/think-and-prep-instructions.ts
Small change to the horizontal  bar chart axis issue changes since it was still failing
=> additional fixes for horizontal charts, hopefully fixing them

apps/server/src/api/v2/chats/cancel-chat.ts
Ensure consistent chat finalization upon cancellation, even when no reasoning or response messages have been created.
=> Handle cancelled chats without reasoning messages

packages/ai/src/steps/post-processing/identify-assumptions-step.ts
Added logic so it talks in first person
Also added logic so it knows that 'relationships' are labeling joins instead of only looking at entities
=> assumption prompt changes for first person voice and join logic

packages/ai/package.json, packages/ai/src/agents/analyst-agent/analyst-agent-instructions.ts, packages/ai/src/agents/think-and-prep-agent/think-and-prep-instructions.ts, packages/ai/src/steps/post-processing/combine-parallel-results-step.ts, packages/ai/src/steps/post-processing/identify-assumptions-step.ts, packages/ai/src/steps/post-processing/schemas.ts, packages/ai/src/tools/post-processing/list-assumptions-response.ts
changes to the assumption prompts to make it catch more things, changes to the main agent so it does not use variables
=> Assumption Prompt / Variable use changes

package.json, packages/ai/src/agents/analyst-agent/analyst-agent-instructions.ts, packages/ai/src/agents/think-and-prep-agent/think-and-prep-instructions.ts, packages/database/package.json, scripts/setup.sh
Added the new setup script + fixed the packages/database/package.json file
Also added a new line in think-and-prep and the analyst to improve the {{Variable}} bug
=> Added setup script + few new changes to address {{variable}} issues

packages/ai/src/steps/post-processing/combine-parallel-results-step.ts, packages/ai/src/steps/post-processing/identify-assumptions-step.ts, packages/ai/src/steps/post-processing/schemas.ts, packages/ai/src/tools/post-processing/list-assumptions-response.ts
More assumption changes related to this ticket
https://linear.app/busterdata/issue/BUS-1436/more-assumption-prompt-changes
=> Fixed some assumption logic

packages/ai/package.json, packages/ai/src/agents/analyst-agent/analyst-agent-instructions.ts, packages/ai/src/agents/think-and-prep-agent/think-and-prep-instructions.ts
Added a fix for the filter tool to try and push it towards creating new metrics
Changes for data existence so that the agent will respond saying it does not have access rather than it does not exist
New eval npm scripts in packages.json
=> Fixes for the filter tool + changes for data existence

apps/api/libs/database/src/helpers/mod.rs, apps/api/libs/database/src/helpers/report_files.rs, apps/api/libs/database/src/types/version_history.rs, apps/api/libs/handlers/src/collections/add_assets_to_collection_handler.rs, apps/api/libs/handlers/src/collections/get_collection_handler.rs, apps/api/libs/handlers/src/collections/remove_assets_from_collection_handler.rs, apps/api/server/src/routes/rest/routes/collections/add_assets_to_collection.rs, apps/api/server/src/routes/rest/routes/collections/remove_assets_from_collection.rs, apps/web/src/controllers/CollectionIndividualController/CollectionIndividualContent.tsx
- Fix report route to use APP_REPORTS_ID instead of APP_REPORT_ID
- Add report icon to CollectionIconRecord
- Add report case to createAssetLink function for proper navigation
=> Add-report-to-collection-functionality

packages/ai/src/workflows/analyst-agent-workflow/analyst-workflow.ts, packages/ai/src/workflows/analyst-agent-workflow/workflow-output.types.ts, packages/ai/src/workflows/index.ts
- Added imports for various dashboard, metrics, and report tools to the analyst workflow.
- Updated the `runAnalystWorkflow` function to return a comprehensive output, including tool call results, charts created, and summary statistics.
- Implemented logic to extract tool calls and segment messages by user requests, improving the overall workflow output structure.
=> Enhance Analyst Workflow with Tool Integration and Output Structuring

apps/cli/src/commands/auth.tsx
- Updated the Auth command to use SafeTextInput for better input handling.
- Simplified input submission logic by creating separate functions for host and API key submissions.
- Removed unused imports and cleaned up the code for improved readability.
=> Refactor Auth command input handling

packages/ai/src/tools/visualization-tools/reports/create-reports-tool/create-reports-execute.test.ts, packages/ai/src/tools/visualization-tools/reports/create-reports-tool/create-reports-execute.ts, packages/ai/src/tools/visualization-tools/reports/modify-reports-tool/modify-reports-execute.test.ts, packages/ai/src/tools/visualization-tools/reports/modify-reports-tool/modify-reports-execute.ts, packages/database/drizzle/0100_wealthy_skaar.sql, packages/database/drizzle/0101_superb_norman_osborn.sql, packages/database/drizzle/meta/0100_snapshot.json, packages/database/drizzle/meta/0101_snapshot.json, packages/database/drizzle/meta/_journal.json, packages/database/src/queries/index.ts, packages/database/src/queries/metrics-to-reports/index.ts, packages/database/src/queries/metrics-to-reports/update-metrics-to-reports.ts, packages/database/src/queries/search/access-control-helpers.ts, packages/database/src/relations.ts, packages/database/src/schema.ts, packages/search/src/asset-search/get-search-result-ancestors.ts
Adding the metric_files_to_report_files table and adding inheritance permissions to search
=> MetricFilesToReportFiles db table

packages/ai/src/agents/analyst-agent/analyst-agent-prompt.txt
Made sure it no longer puts commas in id or year fields
Made it so it stops doing "\$" since it is no longer parsed incorrectly
=> Fixed commas being added and escaping the $ in reports

packages/ai/src/tools/visualization-tools/dashboards/modify-dashboards-tool/modify-dashboards-execute.ts
=> dashboard version fix

packages/ai/src/steps/analyst-agent-steps/mark-message-complete-step/mark-message-complete-step.int.test.ts, packages/ai/src/tools/communication-tools/done-tool/helpers/done-tool-file-selection-report-filtering.test.ts, packages/ai/src/tools/communication-tools/done-tool/helpers/done-tool-file-selection.ts
metric sneaking into the response messages after create
=> fix metric sneaking in

apps/server/src/api/v2/metric_files/[id]/data/GET.ts, apps/server/src/api/v2/metric_files/[id]/data/get-metric-data.ts, packages/server-shared/src/metrics/responses.types.ts
Updates metric_files/[id]/data to include optional password parameter.
=> Add password as optional field for metric_file data

packages/ai/src/agents/analyst-agent/analyst-agent-prompt.txt, packages/ai/src/tools/visualization-tools/metrics/helpers/metric-tool-description.txt
This PR contains hot fixes for colorby functionality (v3).
- Fixes colorby functionality issues
- Updates metric tool descriptions and color grouping logic
This is a hot fix branch addressing colorby-related issues in the visualization tools.
=> Hot fixes for colorby v3

packages/database/drizzle/meta/_journal.json
feature: auto add default shortcuts for orgs.
=> feature: auto add default shortcuts for orgs.

packages/ai/src/tools/communication-tools/done-tool/done-tool-delta.ts, packages/ai/src/tools/communication-tools/done-tool/done-tool-execute.ts, packages/ai/src/tools/communication-tools/done-tool/done-tool-start.test.ts, packages/ai/src/tools/communication-tools/done-tool/done-tool-streaming.test.ts, packages/ai/src/tools/communication-tools/done-tool/done-tool.int.test.ts, packages/database/src/queries/messages/chatConversationHistory.test.ts, packages/database/src/queries/messages/chatConversationHistory.ts
fix: tool use id errors and toolc alls
=> fix on tool use ids and repair calls
